import type { Company, OutreachPackage, Person } from "@workspace/db";
import { AttioApiError, createAttioNote, upsertAttioRecord } from "./attioClient";

export interface AttioRecordPayload {
  objectSlug: string;
  values: Record<string, unknown>;
}

export interface AttioNotePreviewPayload {
  parentObject: string;
  title: string;
  content: string;
}

export interface AttioExportPreview {
  company: AttioRecordPayload;
  person: AttioRecordPayload;
  note: AttioNotePreviewPayload;
}

/**
 * Builds a preview of the exact payloads `syncOutreachPackageToAttio` will send:
 * an upsert to the standard `companies` object, an upsert to the standard
 * `people` object, and a note attached to the person record. This mirrors the
 * real sync 1:1 (down to the attribute slugs) so what you see here is what
 * actually gets written when you sync. Building the preview never calls the
 * Attio API itself.
 */
export function buildAttioExportPreview(input: {
  company: Company;
  person: Person;
  outreachPackage: OutreachPackage;
}): AttioExportPreview {
  const { company, person, outreachPackage } = input;

  const companyPayload: AttioRecordPayload = {
    objectSlug: "companies",
    values: {
      domains: [company.domain],
      name: company.name,
      description: buildCompanyDescription(company),
    },
  };

  const personPayload: AttioRecordPayload = {
    objectSlug: "people",
    values: {
      email_addresses: [person.email],
      name: {
        first_name: person.firstName,
        last_name: person.lastName,
        full_name: `${person.firstName} ${person.lastName}`,
      },
      job_title: person.title,
      company: company.domain,
    },
  };

  const notePayload: AttioNotePreviewPayload = {
    parentObject: "people",
    title: outreachPackage.outreachEmailSubject || `Synthetic GTM Signal: ${outreachPackage.campaign}`,
    content: buildNoteContent(outreachPackage),
  };

  return { company: companyPayload, person: personPayload, note: notePayload };
}

export interface AttioSyncSuccess {
  ok: true;
  companyRecordId: string;
  personRecordId: string;
  personWebUrl: string;
  noteId: string;
  syncedAt: Date;
}

export interface AttioSyncFailure {
  ok: false;
  error: string;
}

export type AttioSyncResult = AttioSyncSuccess | AttioSyncFailure;

/** Formats a company's multi-valued industry/product fields into one readable line. */
function buildCompanyDescription(company: Company): string {
  const industry = company.industry.join(", ");
  return `${industry} · ${company.employeeCount} employees (${company.employeeRange}) · ${company.fundingStage}. ${company.growthSignal}.`;
}

function buildNoteContent(outreachPackage: OutreachPackage): string {
  return [
    "Draft outreach email:",
    "",
    `Subject: ${outreachPackage.outreachEmailSubject || "(not yet generated)"}`,
    "",
    outreachPackage.outreachEmailBody || "(not yet generated)",
    "",
    "---",
    "",
    `Campaign: ${outreachPackage.campaign}`,
    `Source signal: ${outreachPackage.sourceSignal}`,
    `Agent confidence: ${outreachPackage.agentConfidence ?? "n/a"}`,
    "",
    "Behavioral trail:",
    ...outreachPackage.behavioralTrail.map((line) => `- ${line}`),
    "",
    `Behavior summary: ${outreachPackage.behaviorSummary}`,
    "",
    `Research summary: ${outreachPackage.researchSummary}`,
    "",
    `Recommended outreach angle: ${outreachPackage.outreachAngle}`,
    "",
    `Growth hypothesis version: ${outreachPackage.hypothesisVersion}`,
    `Prompt version: ${outreachPackage.promptVersion}`,
    "",
    "This note was generated by the Synthetic GTM Signal Engine demo. The company, " +
      "person, and behavioral data referenced here are synthetic/fictional and were " +
      "generated for demo purposes -- they do not represent a real prospect. The draft " +
      "email above and the research summary/angle below were generated by a real LLM call " +
      "reasoning over this synthetic data.",
  ].join("\n");
}

/**
 * Pushes the company, person, and an outreach note to a real Attio workspace via
 * the Attio REST API. Requires ATTIO_API_KEY to be configured. Never throws --
 * returns a result object so callers can persist success/failure state.
 */
export async function syncOutreachPackageToAttio(input: {
  company: Company;
  person: Person;
  outreachPackage: OutreachPackage;
}): Promise<AttioSyncResult> {
  const { company, person, outreachPackage } = input;

  if (!process.env.ATTIO_API_KEY) {
    return { ok: false, error: "ATTIO_API_KEY is not configured" };
  }

  try {
    const companyRecord = await upsertAttioRecord("companies", "domains", {
      domains: [company.domain],
      name: company.name,
      description: buildCompanyDescription(company),
    });
    const companyRecordId = companyRecord.data.id.record_id;

    const personRecord = await upsertAttioRecord("people", "email_addresses", {
      email_addresses: [person.email],
      name: {
        first_name: person.firstName,
        last_name: person.lastName,
        full_name: `${person.firstName} ${person.lastName}`,
      },
      job_title: person.title,
      company: company.domain,
    });
    const personRecordId = personRecord.data.id.record_id;

    const note = await createAttioNote({
      parentObject: "people",
      parentRecordId: personRecordId,
      title: outreachPackage.outreachEmailSubject || `Synthetic GTM Signal: ${outreachPackage.campaign}`,
      content: buildNoteContent(outreachPackage),
    });

    return {
      ok: true,
      companyRecordId,
      personRecordId,
      personWebUrl: personRecord.data.web_url,
      noteId: note.data.id.note_id,
      syncedAt: new Date(),
    };
  } catch (err) {
    const message =
      err instanceof AttioApiError
        ? `Attio API error (${err.status}): ${err.message}`
        : err instanceof Error
          ? err.message
          : "Unknown error syncing to Attio";
    return { ok: false, error: message };
  }
}
